steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:$BUILD_ID'
      - '.'
    id: 'build-image'

  # Step 2: Push image with BUILD_ID tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:$BUILD_ID'
    id: 'push-image-build-id'

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:latest'
    id: 'push-image-latest'

  # Step 4: Deploy to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'abraham-assgn2-flask-vm'
      - '--zone=us-central1-a'
      - '--container-image=gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:latest'
    id: 'deploy-to-vm'

# Images to store in GCR
images:
  - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/abraham-assgn2-flask-app:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '600s'

# Tags for organization
tags:
  - 'abraham-assgn2'
  - 'flask-app'
  - 'automated-build'
